export const CREATE_CONFERENCE = 'CONFERENCE/CREATE_CONFERENCE';
export const FETCH_CONFERENCES = 'CONFERENCE/FETCH_CONFERENCES';

export const REQUEST_CONFERENCES = 'CONFERENCE/REQUEST_CONFERENCES';

export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const HIDE_LOADER = 'APP/HIDE_LOADER';

export const SHOW_ALERT = 'APP/SHOW_ALERT';
export const HIDE_ALERT = 'APP/HIDE_ALERT';
